In [ ]:
# importing necessary libraries
import pandas as pd
final_df=pd.read_csv('/content/drive/MyDrive/asad123/filer (1).csv')
# final_df.drop(['time_since_start' ,'time_standard',	'peak_production',	'day_of_week'	,'is_weekend',	'time_of_day'	,'season'	,'generation_W_rolling_mean_1h'	,'generation_to_capacity_ratio'],inplace=True,axis=1)
final_df.head(20)

generation_W     load_W  connection_type  location  panels_capacity  \
0            0.0  525.66667                0         9            5.005   
1            0.0  518.90000                0         9            5.005   
2            0.0  528.50001                0         9            5.005   
3            0.0  517.99999                0         9            5.005   
4            0.0  520.90001                0         9            5.005   
5            0.0  523.50000                0         9            5.005   
6            0.0  517.66666                0         9            5.005   
7            0.0  530.70000                0         9            5.005   
8            0.0  517.09999                0         9            5.005   
9            0.0  513.20001                0         9            5.005   
10           0.0  508.00000                0         9            5.005   
11           0.0  512.30000                0         9            5.005   
12           0.0  516.40000                0         9            5.005   
13           0.0  522.00000                0         9            5.005   
14           0.0  516.30000                0         9            5.005   
15           0.0  521.00000                0         9            5.005   
16           0.0  514.44445                0         9            5.005   
17           0.0  511.59999                0         9            5.005   
18           0.0  517.09999                0         9            5.005   
19           0.0  518.77778                0         9            5.005   

    load_capacity  year  month  day  hour  minute  time_standard  \
0             5.5  2023      8   14     1      50              0   
1             5.5  2023      8   14     2       0              0   
2             5.5  2023      8   14     2      10              0   
3             5.5  2023      8   14     2      20              0   
4             5.5  2023      8   14     2      30              0   
5             5.5  2023      8   14     2      40              0   
6             5.5  2023      8   14     2      50              0   
7             5.5  2023      8   14     3       0              0   
8             5.5  2023      8   14     3      10              0   
9             5.5  2023      8   14     3      20              0   
10            5.5  2023      8   14     3      30              0   
11            5.5  2023      8   14     3      40              0   
12            5.5  2023      8   14     3      50              0   
13            5.5  2023      8   14     4       0              0   
14            5.5  2023      8   14     4      10              0   
15            5.5  2023      8   14     4      20              0   
16            5.5  2023      8   14     4      30              0   
17            5.5  2023      8   14     4      40              0   
18            5.5  2023      8   14     4      50              0   
19            5.5  2023      8   14     5       0              0   

    peak_production  day_of_week  is_weekend  time_of_day  season  \
0                 1            0           0            3       2   
1                 1            0           0            3       2   
2                 1            0           0            3       2   
3                 1            0           0            3       2   
4                 1            0           0            3       2   
5                 1            0           0            3       2   
6                 1            0           0            3       2   
7                 1            0           0            3       2   
8                 1            0           0            3       2   
9                 1            0           0            3       2   
10                1            0           0            3       2   
11                1            0           0            3       2   
12                1            0           0            3       2   
13                1            0 

In [ ]:
f.shape

(3686726, 4)

In [ ]:
import pandas as pd
f=pd.read_csv('/content/drive/MyDrive/task1/train_data.csv')
j=pd.read_csv('/content/drive/MyDrive/task1/systems_new.csv')
# Assuming 'system_id' also exists in the right DataFrame ('j')
c=merged_df = pd.merge(f, j, on='system_id', how='inner')
# Alternatively, if you want to join on the index of 'j':
# c=pd.merge(f,j,left_on='system_id', right_index=True, how='inner')



In [ ]:
c.drop('timestamp',axis=1,inplace=True)

# Handling Some scaler issues

In [ ]:
import pandas as pd
# ... (your existing code to create 'c' DataFrame)

new_row = {'system_id': 2, 'generation_W': 0, 'load_W': 300.23, 'connection_type':'COMMERCIAL', 'location':'SHEIKHUPURA', 'panels_capacity':545, 'load_capacity':234}
# system_id timestamp   generation_W    load_W  connection_type location    panels_capacity load_capacity

# Use pd.concat instead of append
c.loc[len(c.index)] = new_row

from sklearn.preprocessing import LabelEncoder
scaler1=LabelEncoder()
scaler2=LabelEncoder()
c['connection_type']=scaler1.fit_transform(c['connection_type'])
c['location']=scaler2.fit_transform(c['location'])

In [ ]:
c['location'] = c['location'].replace('ABBOTTABAD', 'ISLAMABAD')

In [ ]:
c['status'] = c['status'].replace('', 'Completed')

In [ ]:
c

system_id            timestamp  generation_W       load_W  \
0               17  2023-08-14 01:50:00       0.00000    525.66667   
1               17  2023-08-14 02:00:00       0.00000    518.90000   
2               17  2023-08-14 02:10:00       0.00000    528.50001   
3               17  2023-08-14 02:20:00       0.00000    517.99999   
4               17  2023-08-14 02:30:00       0.00000    520.90001   
...            ...                  ...           ...          ...   
3845824         57  2024-08-09 07:40:00    3510.99999   8843.46429   
3845825         57  2024-08-09 07:50:00    3689.99999   8262.64100   
3845826         57  2024-08-09 08:00:00    3868.62502  10244.71429   
3845827         57  2024-08-09 08:10:00    3981.84613   8310.77777   
3845828          2                  NaN       0.00000    300.23000   

         connection_type  location  panels_capacity  load_capacity  
0                      0         9            5.005            5.5  
1                      0         9            5.005            5.5  
2                      0         9            5.005            5.5  
3                      0         9            5.005            5.5  
4                      0         9            5.005            5.5  
...                  ...       ...              ...            ...  
3845824                0         6           19.800           20.0  
3845825                0         6           19.800           20.0  
3845826                0         6           19.800           20.0  
3845827                0         6           19.800           20.0  
3845828                0        15          545.000          234.0  

[3845829 rows x 8 columns]

In [ ]:
v=pd.read_csv('/content/drive/MyDrive/task1/combined_data (2).csv')
v['location'] = v['location'].replace('ABBOTTABAD', 'ISLAMABAD')
v['connection_type']=scaler1.transform(v['connection_type'])
v['location']=scaler2.transform(v['location'])

In [ ]:
v.shape

(938602, 23)

In [ ]:
v.to_csv('/content/drive/MyDrive/asad123/Combinedfile.csv', index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
final_df['Generation_W']=pd.to_numeric(final_df['generation_W'],errors='coerce')
final_df['Load_W']=pd.to_numeric(final_df['load_W'],errors='coerce')
final_df['Panels_capacity']=pd.to_numeric(final_df['panels_capacity'],errors='coerce')
final_df['Load_capacity']=pd.to_numeric(final_df['load_capacity'],errors='coerce')
final_df['Generation_W_rolling_mean_1h']=pd.to_numeric(final_df['generation_W_rolling_mean_1h'],errors='coerce')
final_df['Generation_to_capacity_ratio']=pd.to_numeric(final_df['generation_to_capacity_ratio'],errors='coerce')
final_df['Time_since_start']=pd.to_numeric(final_df['time_since_start'],errors='coerce')

In [ ]:
 final_df.drop(['load_W','panels_capacity','load_capacity','generation_W','time_since_start','generation_W_rolling_mean_1h'	,'generation_to_capacity_ratio'],inplace=True,axis=1)

In [ ]:
final_df.columns


Index(['connection_type', 'location', 'year', 'month', 'day', 'hour', 'minute',
       'time_standard', 'peak_production', 'day_of_week', 'is_weekend',
       'time_of_day', 'season', 'Generation_W', 'Load_W', 'Panels_capacity',
       'Load_capacity', 'Generation_W_rolling_mean_1h',
       'Generation_to_capacity_ratio', 'Time_since_start'],
      dtype='object')

# Making sequences of entire dataset

In [ ]:
x0, X1, X2, X3, X4, X5, X6, X7, X8,X9, X10, X11, X12,X13, X14, X15, X16,X17, y1, y2 = [], [], [], [], [], [], [], [], [], [], [],[],[],[],[],[],[], [], [], []

# Define the length of the sequence
sequence_length = 6  # Number of timesteps in each sequence

# Loop through the DataFrame to create sequences
for i in range(0, final_df.shape[0] - sequence_length):
    # Extract sequences for each feature
    x0.append(final_df.iloc[i:i + sequence_length, 0].values)  # Feature 1
    X1.append(final_df.iloc[i:i + sequence_length, 1].values)  # Feature 2
    X2.append(final_df.iloc[i:i + sequence_length, 2].values)  # Feature 3
    X3.append(final_df.iloc[i:i + sequence_length, 3].values)  # Feature 4
    X4.append(final_df.iloc[i:i + sequence_length, 4].values)  # Feature 5
    X5.append(final_df.iloc[i:i + sequence_length, 5].values)  # Feature 6
    X6.append(final_df.iloc[i:i + sequence_length, 6].values)  # Feature 7
    X7.append(final_df.iloc[i:i + sequence_length, 7].values)  # Feature 8
    X8.append(final_df.iloc[i:i + sequence_length, 8].values)  # Feature 9
    X9.append(final_df.iloc[i:i + sequence_length, 9].values)  # Feature 4
    X10.append(final_df.iloc[i:i + sequence_length, 10].values)  # Feature 5
    X11.append(final_df.iloc[i:i + sequence_length, 11].values)  # Feature 6
    X12.append(final_df.iloc[i:i + sequence_length, 12].values)  # Feature 7
    X13.append(final_df.iloc[i:i + sequence_length, 15].values)  # Feature 8
    X14.append(final_df.iloc[i:i + sequence_length, 16].values)  # Feature 9
    X15.append(final_df.iloc[i:i + sequence_length, 17].values)  # Feature 4
    X16.append(final_df.iloc[i:i + sequence_length, 18].values)  # Feature 5
    X17.append(final_df.iloc[i:i + sequence_length, 19].values)  # Feature 6

    # Extract target values
    y1.append(final_df.iloc[i + sequence_length, 13])  # Target 1 (Column 10)
    y2.append(final_df.iloc[i + sequence_length, 14])  # Target 2 (Column 11)

In [ ]:
x0, X1, X2, X3, X4, X5, X6, X7, X8,X9, X10, X11, X12,X13, X14, X15, X16,X17, y1, y2 = [], [], [], [], [], [], [], [], [], [], [],[],[],[],[],[],[], [], [], []
import numpy as np


# Loading the available numpy saved files for model training

In [ ]:
import numpy as np
x0=np.load('/content/drive/MyDrive/foler fer/X0 (1).npy')
X1=np.load('/content/drive/MyDrive/foler fer/X1 (1).npy')
X2=np.load('/content/drive/MyDrive/foler fer/X2 (1).npy')
X3=np.load('/content/drive/MyDrive/foler fer/X3 (1).npy')
X4=np.load('/content/drive/MyDrive/foler fer/X4.npy')
X5=np.load('/content/drive/MyDrive/foler fer/X5 (1).npy')
X6=np.load('/content/drive/MyDrive/foler fer/X6 (1).npy')
X7=np.load('/content/drive/MyDrive/foler fer/X7 (1).npy')
X8=np.load('/content/drive/MyDrive/foler fer/X8 (1).npy')
X9=np.load('/content/drive/MyDrive/foler fer/X9.npy')
X10=np.load('/content/drive/MyDrive/foler fer/X10.npy')
X11=np.load('/content/drive/MyDrive/foler fer/X11.npy')
X12=np.load('/content/drive/MyDrive/foler fer/X12.npy')
X13=np.load('/content/drive/MyDrive/foler fer/X13.npy')
X14=np.load('/content/drive/MyDrive/foler fer/X14.npy')
X15=np.load('/content/drive/MyDrive/foler fer/X15.npy')
X16=np.load('/content/drive/MyDrive/foler fer/X16.npy')
X17=np.load('/content/drive/MyDrive/foler fer/X17.npy')
y1=np.load('/content/drive/MyDrive/foler fer/y1 (1).npy')
y2=np.load('/content/drive/MyDrive/foler fer/y2 (1).npy')

In [ ]:
print(X5[0])
print(X5[1])
print(X5[2])
print(X5[3])
print(X5[4])
print(X5[5])
print(X5[6])
print(X5[7])
print(X5[8])
print(X5[9])
print(X5[10])
print(X5[11])

[1 2 2 2 2 2]
[2 2 2 2 2 2]
[2 2 2 2 2 3]
[2 2 2 2 3 3]
[2 2 2 3 3 3]
[2 2 3 3 3 3]
[2 3 3 3 3 3]
[3 3 3 3 3 3]
[3 3 3 3 3 4]
[3 3 3 3 4 4]
[3 3 3 4 4 4]
[3 3 4 4 4 4]


In [ ]:
final_df['load_W']

# Converting into numpy **arrays**

In [ ]:
import numpy as np

x0, X2, X3, X4, X5, X6, X7, X8, y1, y2=np.array(x0),np.array(X2),np.array(X3),np.array(X4),np.array(X5),np.array(X6),np.array(X7),np.array(X8),np.array(y1),np.array(y2)

In [ ]:
X9, X10, X11, X12,X13, X14, X15, X16,X17=np.array(X9),np.array(X10),np.array(X11),np.array(X12),np.array(X13),np.array(X14),np.array(X15),np.array(X16),np.array(X17)

In [ ]:
import numpy as np

# Assuming x0, X1, X2, X3, X4, X5, X6, X7, X8, y1, y2 are already numpy arrays
# Save each array individually
np.save('/content/drive/MyDrive/asad123/x0.npy', x0)
np.save('/content/drive/MyDrive/asad123/X1.npy', X1)
np.save('/content/drive/MyDrive/asad123/X2.npy', X2)
np.save('/content/drive/MyDrive/asad123/X3.npy', X3)
np.save('/content/drive/MyDrive/asad123/X4.npy', X4)
np.save('/content/drive/MyDrive/asad123/X5.npy', X5)
np.save('/content/drive/MyDrive/asad123/X6.npy', X6)
np.save('/content/drive/MyDrive/asad123/X7.npy', X7)
np.save('/content/drive/MyDrive/asad123/X8.npy', X8)
np.save('/content/drive/MyDrive/asad123/X3.npy', X9)
np.save('/content/drive/MyDrive/asad123/X4.npy', X10)
np.save('/content/drive/MyDrive/asad123/X5.npy', X11)
np.save('/content/drive/MyDrive/asad123/X6.npy', X12)
np.save('/content/drive/MyDrive/asad123/X7.npy', X13)
np.save('/content/drive/MyDrive/asad123/X8.npy', X14)
np.save('/content/drive/MyDrive/asad123/X6.npy', X15)
np.save('/content/drive/MyDrive/asad123/X7.npy', X16)
np.save('/content/drive/MyDrive/asad123/X8.npy', X17)
np.save('/content/drive/MyDrive/asad123/y1.npy', y1)
np.save('/content/drive/MyDrive/asad123/y2.npy', y2)

# Or save all arrays in a single compressed file
# np.savez_compressed('/content/drive/MyDrive/asad123/data.npz', x0=x0, X1=X1, X2=X2, X3=X3, X4=X4, X5=X5, X6=X6, X7=X7, X8=X8, y1=y1, y2=y2)


NameError: name 'x0' is not defined

# Saving the scalers

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import joblib


# Save the scaler to a file
joblib.dump(scaler, '/content/drive/MyDrive/asad123/minmax_scaler.pkl')
joblib.dump(scaler2, '/content/drive/MyDrive/asad123/minmax_scaler2.pkl')


['/content/drive/MyDrive/asad123/minmax_scaler2.pkl']

In [ ]:
for i in

[0. 0. 0. 0. 0. 0.]
[0.52941176 0.52941176 0.52941176 0.52941176 0.52941176 0.52941176]
[0. 0. 0. 0. 0. 0.]
[0.63636364 0.63636364 0.63636364 0.63636364 0.63636364 0.63636364]
[0.00305089 0.00305089 0.00305089 0.00305089 0.00305089 0.00305089]
[0.04347826 0.08695652 0.08695652 0.08695652 0.08695652 0.08695652]
[1.  0.  0.2 0.4 0.6 0.8]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]
[0.00305089 0.00305089 0.00305089 0.00305089 0.00305089 0.00305089]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0.03341548 0.03343387 0.03345226 0.03347065 0.03348904 0.03350743]


# Reshaping the outputs for model feed

In [ ]:

y1 = y1.reshape(-1, 1)
y2 = y2.reshape(-1, 1)

In [ ]:
y2.shape

(3845822, 1)

In [ ]:
final_df.shape

NameError: name 'final_df' is not defined

In [ ]:
import sklearn.preprocessing
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler2=MinMaxScaler()
x0=scaler.fit_transform(x0)
X1=scaler.fit_transform(X1)
X2=scaler.fit_transform(X2)
X3=scaler.fit_transform(X3)
X4=scaler.fit_transform(X4)
X5=scaler.fit_transform(X5)
X6=scaler.fit_transform(X6)
X7=scaler.fit_transform(X7)
X8=scaler.fit_transform(X8)
X9=scaler.fit_transform(X9)
X10=scaler.fit_transform(X10)
X11=scaler.fit_transform(X11)
X12=scaler.fit_transform(X12)
X13=scaler.fit_transform(X13)
X14=scaler.fit_transform(X14)
X15=scaler.fit_transform(X15)
X16=scaler.fit_transform(X16)
X17=scaler.fit_transform(X17)
y1=scaler2.fit_transform(y1)
y2=scaler2.fit_transform(y2)

# Stacking the the numpy arrays

In [ ]:
import numpy as np

# x0, X1, X2, X3, X4, X5, X6, X7, X8, y1, y2=np.array(x0),np.array(X1),np.array(X2),np.array(X3),np.array(X4),np.array(X5),np.array(X6),np.array(X7),np.array(X8),np.array(y1),np.array(y2)
X=np.stack((x0,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16,X17),axis=2)
Y=np.stack((y1,y2),axis=2)

# Testing the Shapes

In [ ]:
X_train.shape[1], X_train.shape[2]

(6, 17)

In [ ]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


# Building the model

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, TimeDistributed
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

model = Sequential()
# Use input_shape in the first layer
model.add(LSTM(units=50, batch_input_shape=(64,X_train.shape[1], X_train.shape[2]), return_sequences=True))

model.add(LSTM(units=50,return_sequences=False))
model.add(Dense(units=2,activation='linear'))
model.compile(optimizer=Adam(learning_rate=0.001), loss='mean_squared_error')

# Model summary
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (64, 6, 50)               13600     
                                                                 
 lstm_1 (LSTM)               (64, 50)                  20200     
                                                                 
 dense (Dense)               (64, 2)                   102       
                                                                 
Total params: 33902 (132.43 KB)
Trainable params: 33902 (132.43 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
from google.colab import drive
drive.mount('/content/driv')

In [ ]:
model.fit(X_train, Y_train, epochs=5, batch_size=32, validation_split=0.2)

In [ ]:
model.save('/content/driv')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
